### ISSUE TITLE
TypeError: mod.require is not a function

### ISSUE THREAD

**Issue by Djiit** [getsentry/sentry-electron#142] opened 2018-11-09 14:48 UTC
Hello there,

Using electron 3 and sentry-electron 0.13.0, I can't initialise Sentry and get this error when the app starts : 

```
TypeError: mod.require is not a function
    at Object.dynamicRequire (webpack:///./node_modules/@sentry/utils/misc.js?:10:16)
    at Object.specificInit (webpack:///./node_modules/@sentry/electron/dist/dispatch.js?:129:41)
    at init (webpack:///./node_modules/@sentry/electron/dist/sdk.js?:52:16)
    at eval (webpack:///./src/sentry.js?:5:3)
    at Object../src/sentry.js (/Users/jtanay/Projects/misc/desktop-app/dist_electron/index.js:3730:1)
    at __webpack_require__ (/Users/jtanay/Projects/misc/desktop-app/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:9:65)
    at Module../src/background.js (/Users/jtanay/Projects/misc/desktop-app/dist_electron/index.js:3719:1)
    at __webpack_require__ (/Users/jtanay/Projects/misc/desktop-app/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
```

I just copy-pasted the docs from here : https://docs.sentry.io/error-reporting/quickstart/?platform=electron#configure-the-sdk and currently init Sentry only in my background process.

Did I miss something ?

Thanks for you help

**Comment by Superjo149** [comment] 2018-11-10 20:58
Same issue here, I switched back to node & browser for now. This issue also happened in the earlier versions as well. #92

**Comment by alxmiron** [comment] 2018-11-12 16:15
Also got this one

**Comment by rhyek** [comment] 2018-12-08 19:08
I am also getting this when calling `init` in the main process with electron 2.0.9.

**Comment by timfish** [comment] 2018-12-09 16:52
This is almost certainly Webpack related but our config is working fine. If you can supply a minimal reproduction of the issue I might be able to point you in the right direction...

**Comment by Norbz** [comment] 2018-12-14 11:15
Getting the same error here, using Electron 3
We are using the Vue-CLI boilerplate, so you should be able to reproduce the error easily using https://github.com/nklayman/vue-cli-plugin-electron-builder

Not really sure were to start digging thought, first time using Sentry

**Comment by koalalorenzo** [comment] 2019-01-06 19:43
Same error here. I am not sure how to work with it or having a workaround for Webpack.
Any solution?

**Comment by Norbz** [comment] 2019-01-10 21:40
Hi there,

Any progress on this ? This is really a shame we can't use sentry because of a compilation error...

**Comment by HazAT** [comment] 2019-01-11 14:31
I just released `0.15.0`; could you guys try the following, if you have this issue instead of importing and using `init` like:
```
import * as Sentry from '@sentry/electron'
Sentry.init({...});
```

Use `init` on the main process with a deep import like:

```
import { init } from '@sentry/electron/dist/main'
import * as Sentry from '@sentry/electron'
init({...});
```

If this works I will write this into the docs.

**Comment by kairon-v** [comment] 2019-01-12 01:16
I tried the `0.15.0` version and I`m getting the following error:
```
Uncaught TypeError: Cannot read property 'getAppPath' of undefined
    at Object../node_modules/@sentry/electron/dist/main/normalize.js (renderer.dev.js:19327)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/backend.js (renderer.dev.js:18483)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/client.js (renderer.dev.js:18754)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/index.js (renderer.dev.js:19123
``` 
I`m importing like:

```
import { init } from '@sentry/electron/dist/main';

init({
    dsn: '__DSN__',
    enableNative: false,
});
```

**Comment by Bnaya** [comment] 2019-01-28 09:34
I'm having this issue with sentry/browser /:

**Comment by marcello3d** [comment] 2019-02-01 19:54
To make this work in both main and renderer, I ended up monkey-patching the dispatch function:
```typescript
require('@sentry/electron/dist/dispatch').specificInit =
    process.type === 'browser'
        ? require('@sentry/electron/dist/main').init
        : require('@sentry/electron/dist/renderer').init;
```

This is because we're webpacking `node_modules` into our electron app (rather than shipping as node_modules) and we actually really want the normal require rather than the dynamic one electron is trying to use.

What if this project used a normal require, and for webpack builds you can always specify `@sentry/electron` as an external if you don't want it to bundle it.

**Comment by timfish** [comment] 2019-03-04 15:09
We are now bundling both main and renderer processes with webpack. We use:

```
const { init } = (process.type === 'browser'
  ? require('@sentry/electron/dist/main')
  : require('@sentry/electron/dist/renderer'))
```

And then use the Webpack `DefinePlugin`:
```
    // main process
    plugins: [
      new webpack.DefinePlugin({
        'process.type': '"browser"'
      }),

   // renderer process
   new webpack.DefinePlugin({
     'process.type': '"renderer"'
   }),
```

This means that when bundling each process, Webpack replaces `process.type` with a constant and then removes the inaccessible code:
```
const { init } = ('browser' === 'browser'
  ? require('@sentry/electron/dist/main')
  : require('@sentry/electron/dist/renderer'))

// becomes >

const { init } = (true
  ? require('@sentry/electron/dist/main')
  : undefined)
```

**Comment by dperetti** [comment] 2019-09-02 10:12
@HazAT Could this be fixed? It's been one year now and nearly any Electron trying out Sentry will waste hours on this and be left without any satisfactory solution. This is not up to par with Sentry overall quality.

**Comment by rlugge** [comment] 2020-01-30 18:53
@timfish your code is a lifesaver, and should either be merged with Sentry or added to the docs or something.

**Comment by timfish** [comment] 2020-02-01 16:24
@rlugge if it was possible to merge this into Sentry, I would have already submitted a PR 😁.

`sentry-electron` has to cater for many different development scenarios and it prioritises the most common which is bundled renderer and non-bundled main. For this most common scenario, there should be no special bundler configuration required and the renderer should not end up with all the unused Sentry main process code. `dynamicRequire` currently helps fulfil this and if it doesn't for any reason, you should open a new issue about this.

Once the main process is bundled with Webpack, the node `module` object is often not available so the `dynamicRequire` call fails. Even if `module.require()` was available it's likely the `'./main'` code was never bundled. 

Likely the simplest solution is to also expose `InitMain()` and `InitRenderer()` and leave it up to the developer to ensure the correct one is bundled and called, whether that be with help from `webpack.DefinePlugin` or some other means.

**Comment by rlugge** [comment] 2020-02-01 17:35
@timfish while I'm sure all that's true, the 'getting started' guide Sentry pointed me to when I added the project didn't include multiple import statements or an explanation that one was for main, the other for renderer.  It had a single import (don't remember the exact text) that produced the mod.require error.

**Comment by baruchiro** [comment] 2020-02-27 05:54
@timfish I'm working with [`vue-cli-plugin-electron-builder`](https://github.com/nklayman/vue-cli-plugin-electron-builder), and no matter what I'm doing, it didn't work. I'm always getting the next error:

```
ReferenceError: init is not defined
    at eval (webpack:///./src/background.js?:26:1)
    at Module../src/background.js (C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:5691:1)
    at __webpack_require__ (C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:5928:1)
    at __webpack_require__ (C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:20:30)
    at C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:84:18
    at Object.<anonymous> (C:\Users\BaruchR\source\repos\ibs-gui\dist_electron\index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
```
(The `background.js` is the `main` process)

I tried to expose two methods from the module, one for the `main` and one for the `renderer`, like you said.
Then, for these two method I tried to get the correct `init`:

In the top of the module:
```js
import * as Sentry from '@sentry/electron';
import { init as initBackground } from '@sentry/electron/dist/main';
import { init as initRenderer } from '@sentry/electron/dist/renderer';
```

Or in each method:
```js
export function initReporterMain() {
  require('@sentry/electron/dist/main').init(electronOptions);
}

export function initReporterRenderer() {
  require('@sentry/electron/dist/renderer').init(electronOptions);
}
```

None of them worked.
your first solution with `process.type` didn't work, although the `process.type` value was correct, so I think it is something in Webpack.

Importing from `background.js` (the `main` process) doing the work.

**Comment by HazAT** [comment] 2020-07-02 08:07
Sorry for all the wasted time, I added a section in our docs for that.
https://github.com/getsentry/sentry-docs/pull/1835

Closing this ticket for now.

**Closed by HazAT** 2020-07-02 08:07 UTC

**Comment by ton77v** [comment] 2020-07-09 16:17
> And then use the Webpack `DefinePlugin`:
> 
> ```
>     // main process
>     plugins: [
>       new webpack.DefinePlugin({
>         'process.type': '"browser"'
>       }),
> 
>    // renderer process
>    new webpack.DefinePlugin({
>      'process.type': '"renderer"'
>    }),
> ```

Thanks for the solution!

Any ideas how to implement this using vue-cli?

There's a way to modify plugins using chainWebpack
https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin

But I have no ideas how to rewrite this code 🤯
