### ISSUE TITLE
App gets hang when removing text from input

### ISSUE THREAD

**Issue by zuhairnaqi** [getsentry/sentry-electron#400] opened 2021-12-14 18:15 UTC
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [2.5.4] SDK version - `@sentry/electron@v?.?.?`
- [16.0.4] Electron version - `electron@v?.?.?`
- [macOS] Platform - `Windows/macOS/Linux`

## Description

I am using react-hook-form for forms. All things working fine but when I submit the form with wrong data and remove some characters from the input the app gets hang. And a code in the sentry file gets on, on debug.
When I remove sentry init from renderer and main files the issue does not appear.

<img width="958" alt="Screenshot 2021-12-14 at 11 12 57 PM" src="https://user-images.githubusercontent.com/38198958/146056171-2c28bdff-1cff-468a-958b-441618c35315.png">

![Screenshot 2021-12-13 at 7 08 40 PM](https://user-images.githubusercontent.com/38198958/146056149-a10d0d26-c16d-42ee-9f39-8969412f4c80.png)
![Screenshot 2021-12-13 at 7 31 41 PM](https://user-images.githubusercontent.com/38198958/146056157-773b66e3-e033-4ba4-991d-1809db5f7921.png)

**Comment by timfish** [comment] 2021-12-14 18:33
This is potentially caused by something that you're logging to console although I'm not sure of the cause. 
Can you supply a repository that reproduces this so I can try it out myself?

**Comment by zuhairnaqi** [comment] 2021-12-14 19:04
@timfish yeah, the issue went when I remove console.log from the component. But why it is happening?

**Comment by timfish** [comment] 2021-12-14 19:28
I don't know why it's happening but I think I could probably work it out if I could reproduce and debug it on my machine.

**Comment by timfish** [comment] 2022-02-16 13:51
This is a duplicate of #263. Looking into it!

**Closed by timfish** 2022-02-16 13:51 UTC
