### ISSUE TITLE
Anomaly in reported crashed sessions

### ISSUE THREAD

**Issue by jjbayer** [getsentry/sentry-electron#931] opened 2024-06-27 13:12 UTC
A user reported a negative crash-free rate. We figured out that there's a single 10-second interval in which a very high number of crashed sessions was reported, but the number of _total_ sessions remained stable:

![image](https://github.com/getsentry/sentry-electron/assets/1565449/61d66f42-c27d-45e3-941f-0c9fbc1d878f)

This looks suspicious for two reasons:

1. The number itself seems unreasonably high.
2. `sessions.all` must always be larger than `sessions.crashed`. If the crashed number is higher, it means that the SDK reported session updates with `init: false` for which it has never reported the initial update with `init: true`.

Could there be a reporting bug in the electron SDK which causes large numbers of session updates to be flushed without `init: true`?

Zendesk ticket with URL to the API request shown above: https://sentry.zendesk.com/agent/tickets/124592

**Comment by AbhiPrasad** [comment] 2024-11-01 16:33
Closing this for clean up - please re-open if the issue is still there!

**Closed by AbhiPrasad** 2024-11-01 16:33 UTC
