### ISSUE TITLE
TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by Christilut** [getsentry/sentry-electron#568] opened 2022-10-03 19:38 UTC
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v4.0.2`
- [x] Electron version - `electron@v11.5.0`
- [x] Platform - `macOS & Windows`

## Description

Getting this error when exiting my Electron app (easy to simulate with CTRL+C):
```
TypeError: Object has been destroyed
    at log (/Users/chris/workspace/my-app/.webpack/main/index.js:41352:20)
    at App.<anonymous> (/Users/chris/workspace/my-app/.webpack/main/index.js:41573:13)
    at App.emit (events.js:327:22)
    at App.EventEmitter.emit (domain.js:483:12)
    at App.emitter.emit (/Users/chris/workspace/my-app/.webpack/main/index.js:4273:20)
    at App.<anonymous> (electron/js2c/browser_init.js:185:3283)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:483:12)
    at App.emitter.emit (/Users/chris/workspace/my-app/.webpack/main/index.js:4273:20)
    at App.<anonymous> (/Users/chris/workspace/my-app/.webpack/main/index.js:41631:84)
```

Sentry init is the first thing called in the main process:
```
Sentry.init({ dsn: '...' })
```

When I remove the init call, the error disappears.

**Comment by timfish** [comment] 2022-10-05 14:51
That doesn't sound like great behaviour but I can't reproduce this myself and the above stack-trace is minified so I can't tell which event is causing the issue!

Can you modify any of the [examples](https://github.com/getsentry/sentry-electron/tree/master/examples) to trigger this?

**Comment by AbhiPrasad** [comment] 2023-07-27 15:57
Closing this issue for cleanup. Please re-open if this still applies. Thanks!

**Closed by AbhiPrasad** 2023-07-27 15:57 UTC
Labels: Type: Bug, Status: Needs Reproduction
