### ISSUE TITLE
electron: plugin is adding __dirname in preload file after compilation

### ISSUE THREAD

**Issue by SugarDarius** [getsentry/sentry-electron#670] opened 2022-12-22 07:19 UTC
#### Description
This is issue is happening when using the plugin for `electron`  with `electron-forge`. 
An unexpected `__dirname` is written in the source file and cause to the renderer process to fail as it's configured with `nodeIntegration: false`.

What version are you running? Etc.

| package | version |
| -------- | ------- |
| electron | `21.2.2` |
| electron-forge | `6.0.0` |
| @sentry/webpack-plugin | `1.20.0` |
| typescript | `4.8.x` |

### Steps to Reproduce

- GIVEN you're creating a `BrowserWindow` with the webPreference `nodeIntegration` set to `false`
- THEN you're creating a new exposable api calling `ipcRenderer` in the file `preload.ts`
- IF you import some other files using `ipcRenderer` in the file `preload.ts`
- THEN as a result the plugin is adding `__dirname` to target some `/native_modules`

Here's our plugin's config:
```js
    new SentryWebpackPlugin({
      url: process.env.SENTRY_URL,
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,
      authToken: process.env.SENTRY_AUTH_TOKEN,
      include: '.webpack/renderer',
      urlPrefix: '~/.webpack/renderer',
      dist: `desktop-distribution-${pkg.version}`,
      release: `desktop@${pkg.version}`,
      dryRun: isDev,
    }),
```

### Expected Result

What you thought would happen.
- Everything working as it was before using the plugin.
- Please note without the plugin everything is fine, the reference to `"__dirname + "/native_modules/";`  is only added when using the plugin.
- Please also note when using the plugin if every calls to `ipcRenderer` is in the file `preload.ts` then everything is okay surprisingly and `__dirname` is not added.
 
Also our webpack configuration has well the config: 
```js
  {
    test: /native_modules\/.+\.node$/,
    use: 'node-loader',
  },
  {
    test: /\.(m?js|node)$/,
    parser: { amd: false },
    use: {
      loader: '@vercel/webpack-asset-relocator-loader',
      options: {
        outputAssetBase: 'native_modules',
      },
    },
  },
```

### Actual Result
The preload script fails completely with:
```js
VM4 sandbox_bundle:93 ReferenceError: __dirname is not defined
```

What actually happened. Maybe a screenshot/recording? Maybe some logs?
<img width="1366" alt="Screenshot 2022-12-22 at 08 06 04" src="https://user-images.githubusercontent.com/3740000/209077806-74b1223c-5bd9-4a30-9eb8-22766b23b6e3.png">

Webpack compilation result (preload.js):
<img width="883" alt="Screenshot 2022-12-22 at 08 06 24" src="https://user-images.githubusercontent.com/3740000/209078049-420687f4-33f6-42d2-be04-0649ee9a5acc.png">

Thanks a lot for your help 🙏🏻

**Comment by AbhiPrasad** [comment] 2023-04-28 12:19
@timfish could you take a look and help investigate?

**Comment by lforst** [comment] 2023-04-28 12:22
I have a feeling that this is unrelated to our plugin tbh. It may seem like it's the Sentry plugin because the `__dirname` is very close to the code we inject but we don't inject any `__dirname`. Can everybody confirm that this is an issue even after removing the plugin from their pipeline?

**Comment by SugarDarius** [comment] 2023-04-28 12:45
Hi @lforst 👋🏻 

Thanks for you answer 🙏🏻 

However as described in the description:
> Please note without the plugin everything is fine, the reference to "__dirname + "/native_modules/"; is only added when using the plugin.

Meaning in our case I only see the reference to `__dirname` in the webpack compilation result when the sentry plugin is added. If not I don't see any reference. 

But could it be possible based on what you say that it's the combinaison of `@sentry/webpack-plugin` and `@vercel/webpack-asset-relocator-loader` at the same time which could be the source of the issue? 🤔 

Thanks

**Comment by kamilogorek** [comment] 2023-04-28 13:51
That's correct. It's detecting that `sentry-cli` is using precompiled binary and it's moving it around.
See https://github.com/electron/forge/blob/main/packages/plugin/webpack/test/AssetRelocatorPatch_spec.ts which has assertions around it.
And here's what's doing injection https://github.com/electron/forge/blob/e5fc3037340b5bce6f0ba496e92c397ca4803c4f/packages/plugin/webpack/src/util/AssetRelocatorPatch.ts#L47

**Comment by timfish** [comment] 2023-04-28 23:24
> And here's what's doing injection https://github.com/electron/forge/blob/e5fc3037340b5bce6f0ba496e92c397ca4803c4f/packages/plugin/webpack/src/util/AssetRelocatorPatch.ts#L47

Just reading this code and it felt familiar and then realised I wrote it. It's some not pretty hacks to get the vercel loader working with Electron + Forge.

What I find strange here is that the error is being throw at all. The preload context has full access to node.js, even when node integration is disabled so `__dirname` should be defined!

Is the webpack config for the preload scripts fully configurable in Electron Forge now? I didn't used to be but I saw a PR merged recently. You almost certainly don't want to be using the Vercel loader with your preload scripts unless you're loading native modules there. 

With a basic repository that reproduces the issue I could probably give more guidance.

I'll look into it next week since I'm not sure I've tried all these dependencies together before.

**Comment by timfish** [comment] 2023-05-02 09:16
I tried a basic Electron Forge app with:
- webpack 
- preload
- Sentry webpack plugin 
 
I don't see any `__dirname` injected into the preload scripts.

Are you using native modules in the preload scripts? 

I would need a minimal reproduction repository to look any further but it's unlikely this has anything to do with any of the Sentry dependencies.

**Comment by AbhiPrasad** [comment] 2023-07-27 15:59
Closing this issue for cleanup. Please re-open if this still applies. Thanks!

**Closed by AbhiPrasad** 2023-07-27 15:59 UTC
Labels: Status: Needs Reproduction
