### ISSUE TITLE
Sending initial session when created

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#713] opened 2023-08-02 22:42 UTC
In the JS SDK we send the session on creation (when initialized) https://github.com/getsentry/sentry-javascript/blob/develop/packages/browser/src/sdk.ts#L254C1-L255

This doesn't seem to be happening with Electron https://github.com/getsentry/sentry-electron/blob/85f82bc34baadb847ef0a1918dfcaf4b5f00449b/src/main/sessions.ts#L22

I think we need to send that initial session with `init: true` as per https://develop.sentry.dev/sdk/sessions/#important-client-behavior

@timfish this there some case I'm missing here?

**Comment by timfish** [comment] 2023-08-03 14:38
> In the JS SDK we send the session on creation (when initialized) https://github.com/getsentry/sentry-javascript/blob/develop/packages/browser/src/sdk.ts#L254C1-L255
> 
> This doesn't seem to be happening with Electron

The Electron SDK doesn't force sending of session on creation but every session is sent. We can delay app shutdown, finish session and flush and we also persist the session to file so it can be reported as abnormal exit/crashed on next run. This means there is no (or very limited) ways we can drop a session. 

Maybe it's important in the browser SDK to capture sessions on creation because there's no guarantee you'll be able to send anything later?

> It's crucial that the initial session update sent to the system has `init` set to `true`. 

This already occurs with the existing code as can be seen in the objects checked in the e2e tests:
https://github.com/getsentry/sentry-electron/blob/85f82bc34baadb847ef0a1918dfcaf4b5f00449b/test/e2e/test-apps/sessions/javascript-error/session-error.json#L1-L17

My understanding was that you don't need to report a session `ok` before you can report it crashed or with errors. All that matters is that the first session envelope has `init: true`. Overall this means we send less sessions to Sentry but as far as I can tell we have the same reported statistics.

**Comment by timfish** [comment] 2023-08-03 15:36
Ah right, I can see how that could be a problem!

@AbhiPrasad can we just add `hub.captureSession()` and the outcome will be positive for everyone?

**Comment by AbhiPrasad** [comment] 2023-08-03 15:41
> can we just add hub.captureSession() and the outcome will be positive for everyone?

Yup I think this should be fine, but we should sanity check to just make sure.

**Comment by timfish** [comment] 2023-08-03 15:47
> we should sanity check to just make sure

Yep, this should play out in the e2e tests!

**Comment by souredoutlook** [comment] 2023-08-03 15:49
Is there a way to put this behind an experimental flag?

**Comment by souredoutlook** [comment] 2023-08-03 15:55
>why the reason for the experiment?

It will change folk's reporting in a sudden way and Sessions are an alertable data category. If someone adopts this change by accident (version bump) without full knowledge it could blow up in their face.

**Comment by AbhiPrasad** [comment] 2023-08-03 15:56
let's make it an option instead of an experiment then, we can just document it and the re-evaluate if we should change it during the next major version.

**Comment by beyondkmp** [comment] 2023-08-04 07:46
If I set "init" to true, it will trigger a session send during initialization, and another one when app exits. This will increase the session count, ultimately leading to a higher crash-free session rate.

I believe it should only send once during initialization and not again when exiting.

**Comment by AbhiPrasad** [comment] 2023-08-04 13:54
For now we don't have to send on exit, but once we introduce https://github.com/getsentry/sentry-electron/issues/712, we can start adding duration to session to match the mobile SDKs, which means we need the init session and the session update.

**Closed** 2023-08-08 10:45 UTC

**Comment by beyondkmp** [comment] 2023-10-10 08:53
@AbhiPrasad in https://github.com/getsentry/sentry-electron/blob/4072bd74b2f02d10c290d6b8f0c373d549ab7dd3/src/main/integrations/main-process-session.ts#L46, when app quits, this function will trigger a session send again. So there are two sessions in the app lifetime.

**Comment by timfish** [comment] 2023-10-10 09:57
`endSession` should only ends a session if there is an active open ('`ok`) session:
https://github.com/getsentry/sentry-electron/blob/4072bd74b2f02d10c290d6b8f0c373d549ab7dd3/src/main/sessions.ts#L41-L64

**Comment by beyondkmp** [comment] 2023-10-10 12:14
@timfish  The endSession function calls hub.endSession(https://github.com/getsentry/sentry-javascript/blob/develop/packages/core/src/hub.ts#L418), which in turn calls _sendSessionUpdate(https://github.com/getsentry/sentry-javascript/blob/develop/packages/core/src/hub.ts#L475) ultimately calls captureSession(https://github.com/getsentry/sentry-javascript/blob/develop/packages/core/src/hub.ts#L480), so when the app exits, it sends the session to the server once again. This results in sending the session twice - once when the app starts and once when it exits, leading to a duplication in session calculations and a significant increase in the crash-free session rate.

**Comment by timfish** [comment] 2023-10-10 12:18
Can you open a new issue with a reproduction?

Sending the session twice shouldn't matter if the `id` doesn't change.

**Comment by beyondkmp** [comment] 2023-10-10 14:05
Got it, Thanks. Currently, the session ID sent at the start and exit is the same.

**Comment by timfish** [comment] 2023-10-10 15:16
Yep, the `id` is the unique key for the session. Multiple session updates get sent to Sentry for each session. 
The `status`, and number of `errors` will change but if the `id` remains the same, these are status changes for an existing session.
