### ISSUE TITLE
`walk` introduced in 1.5.2 leads to memory leak + crash

### ISSUE THREAD

**Issue by james-criscuolo** [getsentry/sentry-electron#263] opened 2020-08-31 22:41 UTC
## Versions + Platform

- [ >= 1.5.2] SDK version - `@sentry/electron@v?.?.?`
- [ witnessed on 9 and 10 ] Electron version - `electron@v?.?.?`
- [ mac ] Platform - `Windows/macOS/Linux`

## Description

Unfortunately I don't have a reproducible demo to show for this, but it appears the introduction of the `walk` function in `1.5.2` causes my application to endlessly spin when that function is hit for a very certain input (I can't pinpoint it, but it is fully replicable). When this occurs, my entire application would freeze and be unclickable, and eventually it would leak enough memory to crash. `walk` was seemingly introduced to break circular references, but I think in my case it has caused one that does not occur in `1.5.1`.

While I don't have a demo, I can get a maintainer or anyone interested in fixing this set up with my app so they can encounter the issue directly.

**Comment by james-criscuolo** [comment] 2020-12-10 14:07
Commented on the wrong issue a bit ago, it's this issue that still exists in 2.0.4, sorry about that.

**Comment by drinksbydrew** [comment] 2021-02-23 00:56
Seeing this same issue with 2.1.0 as well. Freezes, totally unusable, then crashes. I removed the `Sentry.init(...)` call in the renderer process and it no longer crashes.

**Comment by james-criscuolo** [comment] 2021-03-03 14:41
I just opened that ^ over where @sentry/utils lives, Electron 12 will require the latest @sentry/electron once the latest PR taken is in a release (it may already be).

**Comment by aguynamedben** [comment] 2021-04-15 04:52
cc @HazAT who seemed to introduce usage of `wallk` in 1.5.2

**Comment by aguynamedben** [comment] 2021-04-15 04:55
@james-criscuolo @drinksbydrew I think we might be having our app freezing in the same manner you're describing with @sentry/electron 2.4.0.

I'm still trying to determine if this is the cause. Our users have sent videos and screenshots of the app freezing, but internally at our company we're not able to reliably reproduce this. **Do you know of any contrived ways to reproduce this?**

You say "a very certain input" do you mean an <input> box? Our app is a search app and people use an <input> all day. Any tips on how to trigger this would be greatly helpful. Thanks.

**Comment by HazAT** [comment] 2021-04-15 09:05
We are on it!

**Comment by timfish** [comment] 2021-04-15 09:11
If I'm to stand any chance of fixing this I'm going to need to reproduce it or get a stacktrace.

@james-criscuolo do you still have an app to reproduce this that you can share privately with me?

**Comment by timfish** [comment] 2021-04-15 09:45
@aguynamedben with our production app we see a small trickle of `unresponsive` renderer events from all platforms logged to sentry. Our app does long term data logging so is left running for days. I've witnessed one first hand where the renderer hung when switching back to the app after not being used for hours. We still don't know the cause but have seen something similar from Electron for years so haven't suspected `@sentry/electron`. 

Our initially temporary and now looking Ng term "solution" is to listen for the  `unresponsive` renderer event in the main process and kill + restart the hung renderer. Since our app stores it's state outside of the renderer, we can kill and restart them and continue from where we left off.

What platforms are your users reporting this issue with?

**Comment by james-criscuolo** [comment] 2021-04-15 13:14
I was able to get around this, but I believe I can still create the situation to recreate. We were logging an Array of fairly nested objects, and as soon as the code hits that it would spin. I have it commented out, so I should be able to re-add it and reproduce.

**Comment by james-criscuolo** [comment] 2021-04-16 12:45
I went back to the commit where I was reproducing and can no longer reproduce. I now get a JSON circular reference error instead, and it does not infinite loop. I don't have time at the moment to dig into it and get back to reproducible, sorry.

**Comment by timfish** [comment] 2021-04-16 12:53
@james-criscuolo thanks for checking!

**Comment by timfish** [comment] 2021-04-21 12:42
I've just managed to reproduce this myself locally. In my case console logging a seemingly basic object causes it to go off walking a huge recursive object tree and leaks around 1GB every 10 seconds!

My limited debugging so far suggests that the `walk` function is not correctly detecting circular references in some cases.

**Comment by aguynamedben** [comment] 2021-04-21 17:58
I haven't had time to reproduce this, but I recently I saw some Electron team members asking people to repro bugs in Electron using Electron Fiddle. https://www.electronjs.org/fiddle @timfish it might be worth trying to copy/recreate that exact object in an Electron Fiddle if you have 10 extra mins. I kicked the tires on it the other week and it's pretty good.

**Comment by timfish** [comment] 2021-04-21 18:21
I can reproduce it easily in our production app but I have a feeling that getting anything close to that running in Electron fiddle will take an inordinate amount of time and not bring us any closer to the cause. 

The object that I carelessly `console.log`'ed and made it into breadcrumbs would no doubt have caused issues anyway if it had made it into an event.  Event payloads sizes are limited so it almost certainly makes sense to reduce the depth to < infinity! Something around 100 could be enough any anyone hitting that limit will likely do it only by mistake.

I'm also going to test a few `JSON.stringify(crazyObj, walk)` to see if I can reproduce this in a more isolated fashion.

**Comment by timfish** [comment] 2021-05-26 22:24
For now we've limited the recursion depth to 50 to remove the chance of this happening and this was released in 2.4.1.

**Comment by aguynamedben** [comment] 2021-06-17 05:59
👏 @timfish Thank you. We never had a good repro case proving this was an issue, but it's good to know recursion depth is limited. We'll be testing out 2.5.0 in our next release. Thanks again.

**Comment by timfish** [comment] 2021-07-19 13:50
Even with the depth limited to 50, I've still managed to managed to find a case where I can get a hand and high memory consumption due to logging of a recursive object.

Reopening this for more investigation.

**Comment by alderzhang** [comment] 2021-12-08 07:22
Still exists in 2.5.4, unfortunately I don't have a reproducible demo to show for this, but i can show you the stack.

![image](https://user-images.githubusercontent.com/8778642/145165738-3e8cefc7-54f2-4f70-a5e5-47dbe020900a.png)
![image](https://user-images.githubusercontent.com/8778642/145165773-d385cb9d-71a0-4599-916f-eda47b68c1c4.png)

**Comment by aguynamedben** [comment] 2021-12-08 07:37
@alderzhang Did it crash your app? Bugs like this in the Sentry SDKs are definitely something I'm concerned about, we had a bad one one time that was fixed quickly, but still resulted in a lot of pain for our users and our engineer team.

Is this going to be addressed with urgency?

**Comment by alderzhang** [comment] 2021-12-08 07:46
@aguynamedben Yes, it crash my app. It cause huge error log print per second, then makes render process consumes a large amount of memory in a short time, finally the app will crash due to OOM

**Comment by alderzhang** [comment] 2021-12-08 08:11
Add a logpoint at `walk` function head with format: 'walk-log', key, value, depth, memo.  Then I get log like this.

<img width="1548" alt="wecom-temp-9e1019ace32ab6b286984f16018e46f4" src="https://user-images.githubusercontent.com/8778642/145172084-4e86a6f7-80e2-430a-8483-5deb8442d592.png">

**Comment by alderzhang** [comment] 2021-12-08 08:16
There is another type of stack:

![image](https://user-images.githubusercontent.com/8778642/145172908-7b7291e2-937e-4589-b983-a423609e1147.png)

**Comment by alderzhang** [comment] 2021-12-08 08:35
I think my problem is something wrong(JS Exception) occur while `walk`, then VUE runtime catch it and try to print error log by `console.error`, but sentry catch `console.error` again and try to call `walk` function leads to infinity loop. So, maybe I can fix this by silent VUE warning. Or we need to use some method to prohibit catching exceptions again during the execution of the `walk` function.

**Comment by alderzhang** [comment] 2021-12-08 08:52
Update: silent VUE warnings only makes log not to print, the `walk` function still infinity loop, it means sentry catch exception directly without `console.error`.

**Comment by timfish** [comment] 2021-12-08 11:52
Thanks for the reports. 

> Add a logpoint at walk function head

Logging inside `walk` will cause breadcrumbs and scope updates to be generated which will in turn call walk.

The only time I've been able to trigger this was when we accidentally logged a huge object tree to the console

**Comment by timfish** [comment] 2021-12-08 14:07
@alderzhang It looks like the issue you are seeing is related to this:
https://github.com/getsentry/sentry-javascript/issues/2957

**Comment by alderzhang** [comment] 2021-12-09 03:31
> Thanks for the reports.
> 
> > Add a logpoint at walk function head
> 
> Logging inside `walk` will cause breadcrumbs and scope updates to be generated which will in turn call walk.
> 
> The only time I've been able to trigger this was when we accidentally logged a huge object tree to the console

You are right! Make beforeBreadcrumb always return null solved my problem. 
`
Sentry.init({
  dsn: 'xxx',
  beforeBreadcrumb = (breadcrumb, hint) => null,
});
`

It seems that the problem is caused by the following log printing (just some exception stack, It doesn't seems to have any huge objects).
[localhost-1639020358884.log](https://github.com/getsentry/sentry-electron/files/7681989/localhost-1639020358884.log)

**Comment by timfish** [comment] 2022-03-29 19:57
There's been a lot of improvements to the underlying Sentry SDKs in this area and this will be released in version `3.0.6` of the Electron SDK. Please open a new issue if anyone finds this is still causing issues.

**Closed by timfish** 2022-03-29 19:57 UTC
Labels: Type: Bug, Status: Confirmed

**Comment by HePingLaoSan** [comment] 2022-05-17 05:53
Still exists in 3.0.7, @alderzhang  saved my life

> > Thanks for the reports.
> > > Add a logpoint at walk function head
> > 
> > 
> > Logging inside `walk` will cause breadcrumbs and scope updates to be generated which will in turn call walk.
> > The only time I've been able to trigger this was when we accidentally logged a huge object tree to the console
> 
> @timfish Thanks! You are right, make beforeBreadcrumb always return null solved my problem.
> 
> ```js
> Sentry.init({
>   dsn: 'xxx',
>   beforeBreadcrumb = (breadcrumb, hint) => null,
> });
> ```
> 
> It seems that the problem is caused by the following log printing (just some exception stack, It doesn't seems to have any huge objects). [localhost-1639020358884.log](https://github.com/getsentry/sentry-electron/files/7681989/localhost-1639020358884.log)
