### ISSUE TITLE
Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by mr-Wayne** [getsentry/sentry-electron#109] opened 2018-08-23 11:47 UTC
Hi guys, i throw exception from ipcMain.on and get error:
```
{ Error: ENOENT: no such file or directory, open 'C:\proj\node_modules\@sentry\electron\src\main\backend.ts'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\proj\\node_modules\\@sentry\\electron\\src\\main\\backend.ts' }
```

This first error:
```
Error: err
    at EventEmitter.ipcMain.on (C:\proj\electron\ipc\auth.js:66:11)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (C:\proj\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at WebContents.emitter.emit.args [as emit] (C:\proj\node_modules\@sentry\electron\src\main\backend.ts:324:14)
```

I try catch and send from captureException same error.
And i cant find src dir from 'C:\proj\node_modules\@sentry\electron\src\main\backend.ts'.
But outside ipcMain code parts its work. :(

I use:
```
      "electron": "^1.8.4",
      "react-scripts": "1.1.4",
      "@sentry/electron": "^0.8.1",
```

**Comment by HazAT** [comment] 2018-08-27 06:29
I think this issue is a duplicate of https://github.com/getsentry/sentry-electron/issues/94
We will soon release a new version which fixes this issue.

**Comment by mr-Wayne** [comment] 2018-09-04 06:38
Ok ;(

**Closed** 2018-09-06 11:46 UTC
