### ISSUE TITLE
Slow Scope Flushing to Disk when Crashpad is Enabled

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-electron#967] opened 2024-08-31 22:13 UTC
When crashpad is enabled, then any scope modification will write a file to disk as it appears.  Seemingly this can cause issues if people perform a lot of scope modifications. (See this thread for some discussion about it: https://x.com/Xaymar/status/1830004843630518634)

I think the right course of action at least would be to debounce this.  Worst case you lose a bit of data at crash time.

**Comment by Xaymar** [comment] 2024-08-31 22:57
Angry german idiot from that thread here. As far as I'm aware, the problem is unique to Windows, and mainly caused by a misuse of the Windows API. Microsoft added more and more "hacks" to make poorly written apps compatible, and Sentry just happened to fall into the lap of one of these "hacks". Unfortunately the behavior appears to come from NodeJS/Electrons usage of [libuv](https://libuv.org/), and is outside of Sentry's control - and even outside of NodeJS/Electrons control. 

And even more unfortunately is how damaging the current behavior is, at least when testing with Lychee Slicer. About one hour of having Lychee Slicer open takes off 0.3% of the estimated lifespan of a Samsung 980 Pro 2TB - not a cheap hour for sure. I've been looking through the source code of each library/software, and am trying to find better ways than setting the Read Only flag on the file it writes.

#### So far, these are the ones I came up with:
1. Open/Create the file and directory once at the start of the Scope's lifetime, not closing it until the app closes. Write and Seek in it as needed, then flush after the debouncing interval passed. This will cause you to only ever hit the "hack" behavior once, working around the issue entirely.
2. Write the file using multiple filehandle.write() calls. I don't know why this works better than fsPromises.writeFile, but testing in an isolated test case ends up without the strange requests for synchronous uncached paged I/O. This works even better when manually slicing the file into 4k sections and firing off multiple parallel async writes with set positions (supported on Windows, not supported on Linux/MacOS).
3. The debouncing mentioned above.
4. Flag the file as Read Only manually on every affected app. This is what I'm doing currently so I can still use my PC when an app abuses Sentry's Scope.

**Comment by timfish** [comment] 2024-09-01 01:05
Electron SDK maintainer idiot here 😆

These scope writes are solely for native crashes that take down the entire app. They should already be queued/throttled/debounced and the file should be written at most every 500ms so it sounds like a bug. 

I'll be back at my desk with access to my Windows laptop on Tuesday but I'd be surprised if this issue is Windows only so I'll likely get a chance to look into it before then.

**Comment by Xaymar** [comment] 2024-09-01 09:19
One sleep later, with a clearer head, back at it again. Yesterday I missed a few critical things while trying to save my SSDs from an early death:

1. Lychee Slicer uses @sentry/electron `~0.17.4`
2. @sentry/electron 0.17.4 depends on @sentry/utils `4.6.2 || ~4.6.4`
3. @sentry/utils 4.6.5 uses [writeFileSync](https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options) without debouncing.

Armed with these deadly version numbers (5 years old...) I've traced the behavior through the files:

- [@sentry/hub/scope.ts](https://github.com/getsentry/sentry-javascript/blob/4.6.5/packages/hub/src/scope.ts): This is the content of the `scope.json` file created by the above.
- [@sentry/hub/hub.ts](https://github.com/getsentry/sentry-javascript/blob/4.6.5/packages/hub/src/hub.ts): This creates the Scope object, which ends up with a `storeScope` call in `bindClient`. 
- [@sentry/core/sdk.ts](https://github.com/getsentry/sentry-javascript/blob/4.6.5/packages/core/src/sdk.ts): The `initAndBind` function here calls `bindClient` from above.
- [@sentry/electron/index.ts](https://github.com/getsentry/sentry-electron/blob/v0.17.4/src/main/index.ts): `init` here calls `core.initAndBind` using `MainClient`/`RendererClient`.
- [@sentry/electron/renderer/client.ts](https://github.com/getsentry/sentry-electron/blob/v0.17.4/src/renderer/client.ts): Defines `RendererClient`, inheriting functionality from `BaseClient`. This simply sends an IPC command over Electron's built-in IPC, so this one isn't the cause.
- [@sentry/electron/main/client.ts](https://github.com/getsentry/sentry-electron/blob/v0.17.4/src/main/client.ts): Defines `MainClient`, inheriting functionality from `BaseClient` and `MainBackend`.
- [@sentry/electron/main/backend.ts](https://github.com/getsentry/sentry-electron/blob/v0.17.4/src/main/backend.ts): Defines `storeScope`, clones the Scope, deletes the clones event processors, and calls `update` on `Store`.
- [@sentry/utils/store.ts](https://github.com/getsentry/sentry-javascript/blob/4.6.5/packages/utils/src/store.ts): Defines the `Store` object, which on every `update` calls `set`, and on every `set` tries to call `flush`.

Anything that depends on @sentry/utils <=5.0.4 will have this behavior, which is any @sentry/electron version <=0.17.4. The obvious fix for Lychee Slicer is to update their extremely dated Sentry version, which appears to predate the earliest publicly released versions of it. I'm actually quite surprised (and perplexed) that npm/yarn/... do not have built-in warnings for using extremely old versions when newer versions exist.

I unfortunately wasn't able to figure out why this cycle of writes happens, since Lychee Slicer only calls these things:

1. `require("@sentry/electron");`
2. `.init({dsn: "https://0c981f10d79a44c4bc0be945fe08981f@o540105.ingest.sentry.io/5658025", ...})`
3. `.configureScope(...)`
4. `.captureEvent(...)` - Only called on exceptions and errors, which according to the injected debugger aren't happening that often.

In terms of usage, this seems perfectly normal, until I noticed that `.captureEvent()` is called for anonymous async calls as well. For some reason, Lychee Slicer polls for toast messages from their cloud(?) as soon as the previous poll is done. And [the URL it uses](https://toasts.mango3d.net/poll) does not exist, so once DNS resolve happens once, Windows instantly returns as soon as possible, and NodeJS returns to JavaScript soon after.

The result is this mess.

**Comment by timfish** [comment] 2024-09-02 15:55
> Lychee Slicer uses @sentry/electron ~0.17.4

Oh wow that release is nearly 5 years old. I think the Electron SDK has been completely re-written a couple of times since then. 

The last couple of major versions uses `BufferedWriteStore` to throttle writes for saving scope and we have unit tests to confirm this behaviour on all platforms.

**Comment by timfish** [comment] 2024-09-05 15:04
Closing this since it's fixed in newer versions of the SDK. 

@Xaymar if you manage to make contact with the Lychee devs I'd be happy to help them upgrade!

**Closed by timfish** 2024-09-05 15:04 UTC
